# Generated by Django 3.2.3 on 2021-06-24 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RecIngred', '0002_alter_ingredient_ingred_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Converts',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('list_id', models.IntegerField(db_column='list_id')),
                ('list_name', models.CharField(max_length=120)),
                ('isBought', models.BooleanField(default=False)),
                ('ingred_quantity', models.FloatField()),
                ('ingred_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecIngred.ingredient')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
