# Generated by Django 3.2.3 on 2021-06-14 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingred_id', models.AutoField(db_column='ingred_id', primary_key=True, serialize=False)),
                ('ingred_name', models.CharField(max_length=120)),
                ('ingred_unit', models.CharField(max_length=120)),
                ('ingred_cat', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('rec_id', models.AutoField(db_column='rec_id', primary_key=True, serialize=False)),
                ('rec_name', models.CharField(max_length=120)),
                ('rec_instructions', models.TextField()),
                ('cooking_time', models.FloatField()),
                ('serving_pax', models.IntegerField()),
                ('cuisine', models.CharField(max_length=120)),
                ('rec_type', models.CharField(max_length=120)),
                ('isPublished', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('ingred_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecIngred.ingredient')),
                ('rec_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RecIngred.recipe')),
            ],
        ),
    ]
